### ISSUE TITLE
Renaming master branch to main

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-swift#1]
Hi @chrispomeroyhale,

We're doing this renaming org-wide as per https://github.com/frictionlessdata/project/issues/537. Can you please take a look?

It's as easy as updating the branch name here - https://github.com/frictionlessdata/schema-collaboration/settings/branches - no more actions on Github are needed.

**Comment by chrispomeroyhale** [comment]
I've pushed a `main` branch and confirmed it shouldn't break its dependency on tableschema-swift. Although I am not able to change this project's default branch. Is this something you can do @roll and then I'll remove the `master` branch?
