### ISSUE TITLE
Releasing v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-swift#2]
Hi @chrispomeroyhale,

WDYT on releasing v1 of the libs?

We have a tracker here - https://github.com/frictionlessdata/libraries#current-status

Also, do I understand correctly, that I can add github release badge for the Swift libs? Upd: I see it needs to be released first as there are only tags

**Comment by chrispomeroyhale** [comment]
Yes, @roll I think adding the github release badges makes sense. I've now added the corresponding GitHub releases. Oh, I just noticed the code coverage badges aren't linking to the `main` branches!

This library is intended to be distributed by Swift Package Manager which is decentralized and relies upon git tags in the semver version format (with no "v" prefix or alpha/beta suffix) to determine the latest release. At this time there is no de facto package repository although I have us listed on Swift Package Index:

- https://swiftpackageindex.com/frictionlessdata/datapackage-swift
- https://swiftpackageindex.com/frictionlessdata/tableschema-swift

As for a 1.0 release, I had been working on API breaking changes to how data gets deserialized to be a better fit with idiomatic Swift that would bump us to a new major release. But that kind of refactor isn't critical. This library is derived from a small app I have had on the App Store for ~2.5 years, and has been using the official 0.9 release for about a year without requiring any changes. So 0.9 is a "spiritual" 1.0 release at this point

**Comment by roll** [comment]
@chrispomeroyhale 
Thanks! I fixed the branch in the library listing. 

If it's a de-facto v1 I would suggest pulling the trigger and make it v1 officially, and there are breaking changes later just be using v2 etc. I think it will better communicate the current status of the libs.

Thanks for educating me regarding Swift packaging. If it's based on tags I can rebase the badge on using tags or, alternatively, we can make releases automatically as we do for some other projects - https://github.com/frictionlessdata/frictionless-py/blob/main/.github/workflows/general.yaml#L128-L153

**Comment by roll** [comment]
@chrispomeroyhale Great thanks! :tada:
