### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-swift#3]
# Overview

Travis CI is "dying" so we're migrating all the Frictionless libs to Github Actions.

@chrispomeroyhale 
Do you have time to try the migration? If you don't I can make an attempt

**Comment by chrispomeroyhale** [comment]
@roll You are welcome to give it a go, I likely won't get around to it for awhile.

Of note, Swift Package Index also automatically does some automated building for determining Swift version and platform compatibility. The status isn't showing iOS which it definitely does support. And tests + coverage reports aren't being run and sent like TravisCI was doing.
